Airport file parse
Arjunica/hw4 pull request #10
Opened 2020-10-13 01:12 UTC by QuinnWass

2020-10-13 04:20 UTC, QuinnWass commented
Not quite done but you can review now

2020-10-13 04:27 UTC, Arjunica reviewed
Looks fine to me. @galaxyonfire can you review and approve. I think this set is critical so I want all of us to be on the same page. Thanks

2020-10-13 05:13 UTC, galaxyonfire requested changes
@QuinnWass the parsing logic itself seems fine to me, just see comments for other suggestions

2020-10-13 05:13 UTC, galaxyonfire commented on mergedFiles/airport_server.c
>  #include "airport.h"
already included in airport_server.h, so do we need to re-declare them here?
```suggestion
```

2020-10-13 05:13 UTC, galaxyonfire commented on mergedFiles/airport_server.c
> +airport_info parse_airport_info(std::string line)
maybe we want to move the airport info parsing logic into the airport_scv.c file because it will run when main is called from that file to build the airport data structure.

2020-10-13 21:19 UTC, QuinnWass commented on mergedFiles/airport_server.c
>  #include "airport.h"
Header guards will filter this out. I like to make my deps explicit.

2020-10-13 21:19 UTC, QuinnWass commented on mergedFiles/Makefile
> +CFLAGS += -g -I/usr/include/tirpc -Wall -MMD -std=c++14
Will remove

2020-10-13 21:20 UTC, QuinnWass commented on mergedFiles/airport_server.c
> +	std::vector<airport_info>* airport_list = new std::vector<airport_info>();
Made it unique

2020-10-13 21:26 UTC, QuinnWass commented on mergedFiles/airport_server.c
> +airport_info parse_airport_info(std::string line)
Lets leave for now.

2020-10-13 21:27 UTC, QuinnWass commented on mergedFiles/Makefile
> +CFLAGS += -g -I/usr/include/tirpc -Wall -pedantic -std=c++14
Thoughts on this?

2020-10-13 22:14 UTC, Arjunica commented on mergedFiles/Makefile
> +CFLAGS += -g -I/usr/include/tirpc -Wall -pedantic -std=c++14
isn't cs1 on c++11?

2020-10-13 22:18 UTC, QuinnWass commented on mergedFiles/Makefile
> +CFLAGS += -g -I/usr/include/tirpc -Wall -pedantic -std=c++14
https://gcc.gnu.org/onlinedocs/gcc-8.3.0/libstdc++/manual/ looks like we can go up to c++ 17

2020-10-13 22:32 UTC, galaxyonfire commented on mergedFiles/Makefile
> +CFLAGS += -g -I/usr/include/tirpc -Wall -pedantic -std=c++14
with `-pedantic` we'll keep getting these compiler warnings even though it's fine if they exist:
![image](https://user-images.githubusercontent.com/40287291/95922152-2fa2e600-0da2-11eb-809d-c16285ab7958.png)
I checked and all the other projects had those "unused" variables. I think rpcgen does not strictly comply to ISO C/C++, so `-pedantic` may be more annoying than useful.

2020-10-14 00:29 UTC, QuinnWass commented on mergedFiles/Makefile
> +CFLAGS += -g -I/usr/include/tirpc -Wall -pedantic -std=c++14
Ok will remove it

2020-10-14 02:03 UTC, galaxyonfire approved these changes
looks good

2020-10-14 02:05 UTC, merged