reorganize
Arjunica/hw4 pull request #17
Opened 2020-10-14 03:48 UTC by galaxyonfire

Closes #11

2020-10-14 05:00 UTC, QuinnWass requested changes

2020-10-14 05:00 UTC, QuinnWass commented on unit_tests/airport_server_unit_tests.c
>  #include <assert.h>
Lets remove merged files and make a unit tests dir and a data dir

2020-10-14 05:17 UTC, galaxyonfire commented on unit_tests/airport_server_unit_tests.c
>  #include <assert.h>
merged files and a new unit tests dir are already part of the pr, I can make a data dir for the places/airport info

2020-10-14 15:59 UTC, Arjunica reviewed
It looked fine to me

2020-10-15 03:25 UTC, QuinnWass approved these changes

2020-10-15 03:25 UTC, QuinnWass commented
Make sure it still runs fine :)

2020-10-15 04:10 UTC, galaxyonfire commented
![image](https://user-images.githubusercontent.com/40287291/96076225-58a7a180-0e9c-11eb-81b4-8a2a655b26de.png)
@QuinnWass getting this error when trying to run unit tests, any ideas?

2020-10-15 04:14 UTC, QuinnWass commented
I had that issue earlier. The vector is empty.

2020-10-15 04:15 UTC, QuinnWass commented
Make sure main is merged in right

2020-10-15 04:20 UTC, QuinnWass requested changes
Redo this, just deleted places and airport server. Leave merged alone as incremental step.

2020-10-15 04:23 UTC, galaxyonfire commented
do you know which commit you did to fix that bug? this branch started after commit 7fbb580f577ed2110d239efae3d85cd98eb24511

2020-10-15 04:24 UTC, QuinnWass commented
Main is passing.

2020-10-15 05:29 UTC, galaxyonfire commented
@QuinnWass fixed it, do you mind confirming it works on your end?

2020-10-16 00:39 UTC, Arjunica requested changes
you will need to merge the latest code from main into this branch before review. ALSO in lieu of 4800 class, lets get rid of testing and just do code reviews 💯

2020-10-16 00:41 UTC, QuinnWass commented
Try reverting to  main, pull in changes, rm the places and airport folders, and git mv the files. Git will recognize the move instead of delete

2020-10-18 07:32 UTC, galaxyonfire commented
what do you guys think of renaming mergedFiles to src? Additionally, do we want to lift the Makefile to root or just keep it in the folder?

2020-10-18 21:20 UTC, QuinnWass commented
Great idea

2020-10-18 21:22 UTC, QuinnWass approved these changes

2020-10-19 05:54 UTC, Arjunica approved these changes
Approved. I saw one issue in the how to run section but I can just fix that in my branch when I do the readme

2020-10-19 05:55 UTC, merged