Fix input
Arjunica/hw4 pull request #22
Opened 2020-10-16 03:59 UTC by QuinnWass

There was an infinite loop with scanf. Works as expected with cin.

2020-10-16 05:35 UTC, Arjunica requested changes
scanf("City: %s", city); 

is the correct was I believe. the state does not need to be re-read since we only need a long prefix on city. I done goofed sorry. Infinite loop cuz its scanning for input its never gonna get. 

Also unrelated but let's try to stick to one coding language standard. there is c all over the place and c++ in different places..

2020-10-16 05:35 UTC, Arjunica commented on mergedFiles/places_client.c
> +		cin >> state;
scanf("City: %s", city); 

is the correct was I believe. the state does not need to be re-read since we only need a long prefix on city. I done goofed sorry. Infinite loop cuz its scanning for input its never gonna get.

2020-10-16 20:55 UTC, galaxyonfire requested changes

2020-10-16 20:55 UTC, galaxyonfire commented on mergedFiles/places_client.c
>  		printf("Could not narrow down city and state. Please give longer name for the city\n");
I think it would be far more effective to just quit the program instead of looping and waiting for more input. Far less headache on our end and Dr. Zhu can just rerun the client program, which i think he's fine with.

2020-10-16 20:57 UTC, Arjunica commented on mergedFiles/places_client.c
>  		printf("Could not narrow down city and state. Please give longer name for the city\n");
I think Zhu clearly said you have to ask client for clearer city if its not a first time hit. I looped it 5 times so that you don't infitely loop but maybe we can reduce it so its the initial guess + 2 more attempts then it exits.

2020-10-16 21:06 UTC, galaxyonfire commented on mergedFiles/places_client.c
>  		printf("Could not narrow down city and state. Please give longer name for the city\n");
Ah i see, it's on end of section 3, my b.

2020-10-17 23:45 UTC, Arjunica commented
Can we close this issue? I think this has been resolved. I will fix in my branch using scanf while additionally handling case of bad state and city. Thank

2020-10-18 02:39 UTC, QuinnWass commented
SGTM

On Sat, Oct 17, 2020 at 4:45 PM Arjunica <notifications@github.com> wrote:

> Can we close this issue? I think this has been resolved. I will fix in my
> branch using scanf while additionally handling case of bad state and city.
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Arjunica/hw4/pull/22#issuecomment-711094443>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADG5ARZFXBMPP6XHBZW5V6DSLIUBFANCNFSM4SSZZ6AA>
> .
>

2020-10-18 05:05 UTC, closed without merging