Kd tree
Arjunica/hw4 pull request #39
Opened 2020-10-19 23:06 UTC by galaxyonfire

closes #26 #25

2020-10-21 04:24 UTC, galaxyonfire commented
unit tests pass on cs1.

2020-10-21 04:28 UTC, galaxyonfire commented
You should be able to do a full client -> places -> airport test now. Sadly my airport_server is unable to register :/

2020-10-21 23:16 UTC, QuinnWass commented on src/airport_svc.c
> +extern kdTree kd_tree;
Consider modeling this off of how I did the prefix trie. However if this works Im fine with it.

2020-10-21 23:18 UTC, QuinnWass requested changes

2020-10-21 23:18 UTC, QuinnWass commented on src/kdTree.h
> +    ~kdTree() = default;
You need to clean up your memory. You are using heap allocated memory.

2020-10-21 23:18 UTC, QuinnWass commented on src/kdTree_unit_tests.c
> +    for (size_t i = 0; i < list.size(); ++i)
Assert expected outcomes.

2020-10-22 01:24 UTC, QuinnWass commented on src/kdTree.c
> +    this->location = location;
@Arjunica  Pls confirm this works as expected. I am pretty sure it does.

2020-10-22 01:53 UTC, Arjunica commented
I will try but @galaxyonfire needs to merge main in....

2020-10-22 02:07 UTC, Arjunica commented
<img width="550" alt="Screen Shot 2020-10-21 at 7 02 54 PM" src="https://user-images.githubusercontent.com/8902297/96811075-a490a400-13d0-11eb-9ba0-953cba6e0365.png">
compiles fine and runs but seems like we getting a negative one return....

2020-10-22 02:17 UTC, galaxyonfire commented
@Arjunica there is no -1 case I throw rn, may be a different error

2020-10-22 02:22 UTC, Arjunica requested changes
Please merge in main then request review. Thanks =)

2020-10-22 02:22 UTC, galaxyonfire commented on src/kdTree.h
> +    ~kdTree() = default;
updated and verified via valgrind

2020-10-22 02:22 UTC, galaxyonfire commented on src/kdTree_unit_tests.c
> +    for (size_t i = 0; i < list.size(); ++i)
added

2020-10-22 02:29 UTC, galaxyonfire commented
@Arjunica 
the issue is you never set result.status to 0 on the positive case:
https://github.com/Arjunica/hw4/blob/c8ec45beb1ba0ad754dddf3e869fc6654d5e3b94/src/places_server.c#L76-L93
so places_client never gets result.status == 0

2020-10-22 02:39 UTC, galaxyonfire commented
Separate issue but I tried to retype in an answer and I got an infinite loop
![image](https://user-images.githubusercontent.com/40287291/96817890-d543fe00-140f-11eb-958d-dc02a9d10d39.png)
![image](https://user-images.githubusercontent.com/40287291/96817800-a0d04200-140f-11eb-9221-d1af36b96744.png)

2020-10-22 02:40 UTC, Arjunica commented
I'll hotfix it tn

Thanks,
--Arjun

On Wed, Oct 21, 2020, 7:29 PM galaxyonfire <notifications@github.com> wrote:

> @Arjunica <https://github.com/Arjunica>
> the issue is you never set result.status to 0 on the positive case:
>
> https://github.com/Arjunica/hw4/blob/c8ec45beb1ba0ad754dddf3e869fc6654d5e3b94/src/places_server.c#L76-L93
> so places_client never gets result.status == 0
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Arjunica/hw4/pull/39#issuecomment-714181490>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACD5NGJ42SWG3DFMFYG6TZLSL6KIHANCNFSM4SW5UE3A>
> .
>

2020-10-22 02:41 UTC, Arjunica commented
Lol I got that too. I think it's cuz the error status does don't get
set....

Thanks,
--Arjun

On Wed, Oct 21, 2020, 7:39 PM galaxyonfire <notifications@github.com> wrote:

> Separate issue but I tried to retype in an answer and I got an infinite
> loop
> [image: image]
> <https://user-images.githubusercontent.com/40287291/96817890-d543fe00-140f-11eb-958d-dc02a9d10d39.png>
> [image: image]
> <https://user-images.githubusercontent.com/40287291/96817800-a0d04200-140f-11eb-9221-d1af36b96744.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Arjunica/hw4/pull/39#issuecomment-714184455>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACD5NGKUSS22SCPKHBKNRGTSL6LP5ANCNFSM4SW5UE3A>
> .
>

2020-10-22 02:42 UTC, galaxyonfire commented
Been trying to enter in correct city/state but keep getting that error :(
![image](https://user-images.githubusercontent.com/40287291/96818043-379cfe80-1410-11eb-8fd4-b355f13df4e8.png)

2020-10-23 03:36 UTC, Arjunica approved these changes

2020-10-23 03:44 UTC, merged